### ISSUE TITLE
useClientEffect outdated?

### ISSUE THREAD

**Issue by findborg** [bryanhannes/qwikchat#1]
I am getting an error with the useClientEffect.  Should I be using something different?  
FYI,  I am learning a lot working with this.  
I can not wait to get it working!  I think you will like what I am trying to do with your code.

**Comment by findborg** [comment]
I think that I have things kinda working.  But,  I am getting a 401 when trying to connect to openai
`
 headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',
      Authorization: 'Bearer undefined'
    },
    method: 'get',
    url: 'https://api.openai.com/v1/models',
    data: undefined
`

What do you think?

**Comment by bryanhannes** [comment]
@findborg Did you rename .env.example to .env and added your OpenAI API key to the file? If not, can you try this, please?
If the issue keeps occurring, I will update the code to the latest Qwik version and make it work again :)

**Comment by findborg** [comment]
I entered like this
OPENAI_API= sk-hMRQqjU2AquS6blbA..................
Is is supposed to be in quotes or some other format?
Now I will tell you that I am not using your build as is.  I am building under another route.  As I worked through it.  I quit getting the useClientEffect errror.   Now I only get the 401 connection problem.

**Comment by findborg** [comment]
@bryanhannes If you like you can email me at fitzflood@gmail.com and I will wrap up my whole package and send to you so that you can see.

**Comment by bryanhannes** [comment]
@findborg I send you an email!

**Comment by bryanhannes** [comment]
UseClientEffect is indeed now outdated in the latest Qwik versions. Change UseClientEffect to useBrowserVisibleTask$.
